# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('recorded', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.Metric')),
            ],
        ),
    ]
