# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial-metrics-migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
