# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_add-server-owner-migration'),
        ('metrics', '0001_initial-metrics-migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server'),
            preserve_default=False,
        ),
    ]
