# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_link-reading-server-migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='unit',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
