# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_add-server-info-to-server-model-migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
