# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_remove-community-migration'),
        ('users', '0002_update-users-migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='community',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
