# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_added_server-log-migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverlog',
            options={'ordering': ['-recorded']},
        ),
    ]
