# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_added_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('cpu_model', models.CharField(blank=True, max_length=100)),
                ('core_count', models.SmallIntegerField(blank=True)),
                ('core_freq', models.FloatField(blank=True)),
                ('max_mem', models.PositiveIntegerField(blank=True)),
                ('game_version', models.CharField(blank=True, max_length=100)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
        ),
    ]
