# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_add-server-info'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='game_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='server',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servers.Server'),
        ),
    ]
