# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metrics', '0003_update-metric-migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('braintree_id', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('retention', models.IntegerField()),
                ('hidden', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('metrics', models.ManyToManyField(to='metrics.Metric')),
            ],
        ),
    ]
